In [1]:
import pandas as pd
import numpy as np
import pickle
import matplotlib.pyplot as plt
from sklearn import tree

In [2]:
dataset = pd.read_csv("dataset.csv")

In [3]:
dataset

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  \
0                3              5             6    86   81   84       87   
1                2              1             3    90   90   88       87   
2                1              5             4    92   91   89       89   
3                5              6             3    90   92   91       90   
4                3              2             3    92   90   89       88   
..             ...            ...           ...   ...  ...  ...      ...   
495              5              4             3    85   90   86       88   
496              3              4             2    85   90   86       88   
497              3              4             2    94   97   91       95   
498              4              2             3    84   93   91       96   
499              2              4             4    88   93   92       86   

     CLASS  
0        1  
1        1  
2        1  
3        1  
4        1  
..     ...  
495      4  
496      4  
497      4  
498      4  
499      4  

[500 rows x 19 columns]

In [4]:
riasec = ["Realistic", "Investigate", "Artistic", "Social", "Enterprising", "Conventional"]
learning_style = ["Linguistic", "Logical-mathematical", "Spatial", "Bodily-Kinesthetic", "Musical", "Interpersonal", "Intrapersonal", "Naturalistic",]

In [5]:
# dataset[riasec] = dataset[riasec]/7 *100
# dataset[learning_style] = dataset[learning_style]/8 *100

In [6]:
X = dataset.iloc[:, 0:18]
y = dataset.iloc[:, 18]

In [7]:
X

Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  
0                3              5             6    86   81   84       87  
1                2              1             3    90   90   88       87  
2                1              5             4    92   91   89       89  
3                5              6             3    90   92   91       90  
4                3              2             3    92   90   89       88  
..             ...            ...           ...   ...  ...  ...      ...  
495              5              4             3    85   90   86       88  
496              3              4             2    85   90   86       88  
497              3              4             2    94   97   91       95  
498              4              2             3    84   93   91       96  
499              2              4             4    88   93   92       86  

[500 rows x 18 columns]

In [8]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)

In [9]:
#from sklearn.preprocessing import StandardScaler

#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)

In [10]:
from sklearn.ensemble import RandomForestClassifier

regressor = RandomForestClassifier(n_estimators=100,  criterion='gini', random_state=0)
regressor.fit(X_train, y_train)

RandomForestClassifier(random_state=0)

In [11]:
y_pred = regressor.predict(X_test)

In [12]:
print(y_test.to_numpy())

print(y_pred)

[1 3 3 4 4 1 3 4 2 2 2 3 4 3 2 3 4 3 2 1 2 3 2 1 1 4 1 3 1 2 4 1 1 2 3 4 3
 4 3 2 3 1 4 2 1 1 2 3 4 1 3 2 3 2 2 1 3 2 2 3 1 3 4 4 3 2 1 4 3 1 2 1 3 4
 2 3 3 1 4 3 3 2 4 2 3 3 4 2 3 1 2 4 4 2 2 3 1 4 1 2 1 3 1 4 1 4 1 2 3 2 3
 1 2 1 4 4 4 3 2 2 4 1 2 3 4 2 1 4 4 4 4 2 3 1 3 4 4 4 4 2 2 1 1 1 4 1 3 3
 2 1]
[1 3 3 4 4 1 3 2 2 2 2 3 4 3 2 3 4 3 2 1 2 3 2 1 1 4 4 3 1 2 4 1 1 2 3 2 3
 4 3 2 3 1 4 2 1 1 2 3 4 1 3 2 3 2 2 1 3 2 2 3 1 3 4 4 3 2 1 4 3 1 2 1 3 4
 2 3 3 1 2 3 3 2 4 2 3 3 4 2 3 1 2 4 4 2 2 3 1 4 1 2 1 3 1 4 4 2 1 2 3 2 3
 1 2 1 4 4 4 3 2 2 4 3 2 3 4 2 4 2 4 4 4 2 3 3 3 4 4 4 4 2 2 1 1 1 4 1 3 3
 2 3]


In [13]:
#FEATURE IMPORTANCE

In [14]:
feature_list = list(X.columns)
feature_imp = pd.Series(regressor.feature_importances_, index=feature_list).sort_values(ascending=False)

In [15]:
print(feature_imp)

Bodily-Kinesthetic      0.119991
Intrapersonal           0.106399
Realistic               0.104313
ENG                     0.079427
Investigate             0.067780
Linguistic              0.064238
Musical                 0.061932
Logical-mathematical    0.051630
Artistic                0.050373
Spatial                 0.044244
Interpersonal           0.041346
SOC-SCI                 0.035256
MATH                    0.034472
Naturalistic            0.032976
Social                  0.032723
Enterprising            0.031398
SCI                     0.025042
Conventional            0.016461
dtype: float64


In [16]:
#CONFUSION MATRIX

In [17]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(accuracy_score(y_test, y_pred))

[[30  0  3  3]
 [ 0 38  0  0]
 [ 0  0 39  0]
 [ 0  5  0 32]]
              precision    recall  f1-score   support

           1       1.00      0.83      0.91        36
           2       0.88      1.00      0.94        38
           3       0.93      1.00      0.96        39
           4       0.91      0.86      0.89        37

    accuracy                           0.93       150
   macro avg       0.93      0.92      0.92       150
weighted avg       0.93      0.93      0.93       150

0.9266666666666666


In [18]:
filename = 'random_forest_model.sav'
pickle.dump(regressor, open(filename, 'wb'))


In [22]:
fn=np.array(dataset.columns[:-1])
cn=["STEM", "HUMSS", "ABM", "GAS"]

fig, axes = plt.subplots(nrows = 1,ncols = 1,figsize = (10,10), dpi=1020)
tree.plot_tree(regressor.estimators_[0],
               feature_names = fn, 
               class_names=cn,
               max_depth=8,
               filled = True);
fig.savefig('rf_individualtree.png')

In [27]:
#train
# 70%

# 30%

C:\Users\sheesh\Desktop\AERY_\venv\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[0.13, 0.18, 0.07, 0.62]])

In [ ]:
regressor.predict_proba([[3,1,2,4,2,3,4,6,4,5,4,3,2,1,97,95,92,97]])


In [28]:
X



Realistic  Investigate  Artistic  Social  Enterprising  Conventional  \
0            3            2         3       1             4             4   
1            5            7         6       3             2             6   
2            4            3         2       4             2             4   
3            4            0         1       6             4             6   
4            4            4         1       2             1             4   
..         ...          ...       ...     ...           ...           ...   
495          4            3         3       4             4             3   
496          4            3         3       4             3             5   
497          4            3         3       4             5             3   
498          4            3         3       4             3             5   
499          4            3         3       4             3             5   

     Linguistic  Logical-mathematical  Spatial  Bodily-Kinesthetic  Musical  \
0             4                     5        5                   5        6   
1             1                     1        2                   1        1   
2             4                     4        4                   3        2   
3             2                     3        4                   5        3   
4             2                     6        5                   1        5   
..          ...                   ...      ...                 ...      ...   
495           7                     3        4                   5        3   
496           4                     5        3                   3        2   
497           4                     5        3                   3        2   
498           7                     5        3                   5        3   
499           2                     6        3                   5        8   

     Interpersonal  Intrapersonal  Naturalistic  MATH  ENG  SCI  SOC-SCI  
0                3              5             6    86   81   84       87  
1                2              1             3    90   90   88       87  
2                1              5             4    92   91   89       89  
3                5              6             3    90   92   91       90  
4                3              2             3    92   90   89       88  
..             ...            ...           ...   ...  ...  ...      ...  
495              5              4             3    85   90   86       88  
496              3              4             2    85   90   86       88  
497              3              4             2    94   97   91       95  
498              4              2             3    84   93   91       96  
499              2              4             4    88   93   92       86  

[500 rows x 18 columns]

In [ ]:
#fn=np.array(dataset.columns[:-1])
#cn=["STEM", "HUMSS", "ABM", "GAS"]

#fig, axes = plt.subplots(nrows = 1,ncols = 5,figsize = (10,2), dpi=900)
#for index in range(0, 5):
#    tree.plot_tree(regressor.estimators_[index],
#                   feature_names = fn, 
#                   class_names=cn,
#                   filled = True,
#                   max_depth=5,
#                   ax = axes[index]);

#    axes[index].set_title('Estimator: ' + str(index), fontsize = 11)
#fig.savefig('rf_5trees.png')